echo_run: 0  # run SV callers [0] or vanilla jobs [1]
enable_callers:
    - manta
    - delly
    - lumpy
    - gridss

# file path to the reference genome in FASTA (excl. file suffix)
genome_path: data/fasta/Homo_sapiens.GRCh37.GATK.illumina

file_exts:
  fasta: .fasta
  fasta_idx:
    - .fasta.fai  # faidx index file
    - .fasta.bwt  # bwa v0.6.x
    - .fasta.amb  # index files
    - .fasta.ann  #
    - .fasta.pac  #
    - .fasta.sa   #
  bam: .bam
  bam_idx: .bam.bai

samples: samples.csv  # TUMOR/NORMAL sample pairs (*.bam files incl. PATH)

callers:
  manta:
    threads: 24
    memory: 16384  # MB
    tmpspace: 0  # min. temporary disk space in MB
    outdir: manta_out  # abspath or relative to current working dir

  delly:
    threads: 2
    memory: 4096
    tmpspace: 0
    outdir: delly_out
    sv_types:
        - BND
        - DEL
        - DUP
        - INS
        - INV

  lumpy:
    threads: 1
    memory: 32768
    tmpspace: 0  # 1024
    outdir: lumpy_out

  gridss:
    threads: 24
    memory: 63488
    tmpspace: 0  # 10240
    outdir: gridss_out
