sudo: true
dist: trusty
language: python
python:
  - "3.6"
services:
  - docker
env:
  - MODE=s PORT=10022 SCH=gridengine JID="\$JOB_ID"
  - MODE=g PORT=10023 SCH=gridengine JID="\$JOB_ID"
  - MODE=s PORT=10024 SCH=slurm JID="%j"
  - MODE=g PORT=10025 SCH=slurm JID="%j"
addons:
  apt:
    update: true
    packages:
      - sshpass
install:
  - docker pull gtcg/sv-callers-$SCH
  - docker run -d -p $PORT:22 gtcg/sv-callers-$SCH
  - sleep 10
  - docker ps -a
script:
  - |
    sshpass -p javagat ssh xenon@localhost -p $PORT \
      -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
      "/bin/bash -lc \"cd sv-callers/snakemake && \
      git checkout dev && snakemake -C echo_run=1 mode=$MODE --use-conda \
      --latency-wait 30 --jobs --cluster 'xenon -vvv scheduler $SCH \
      --location local:// submit --name smk.{rule} --inherit-env \
      --max-run-time 1 --working-directory . --stderr stderr-$JID.log \
      --stdout stdout-$JID.log' && ls\""
