dist: trusty
sudo: required
language: python
python:
  - "3.6"
services:
  - docker
env:
  global:
    - PREFIX=gtcg/sv-callers
  matrix:
    - MODE=s PORT=10022 SCH=gridengine
    - MODE=p PORT=10023 SCH=gridengine
    - MODE=s PORT=10024 SCH=slurm
    - MODE=p PORT=10025 SCH=slurm
before_install:
  - docker pull $PREFIX-$SCH
  - docker run -d -p $PORT:22 --name $SCH-$MODE $PREFIX-$SCH
  - sleep 10
  - docker ps -a
  - docker cp run.sh $SCH-$MODE:/home/xenon
install: true
script:
  - docker exec -u xenon -t $SCH-$MODE /bin/bash run.sh $MODE $SCH
