language: python
sudo: false
dist: trusty
python:
  - "3.6"
before_install:
  - cd snakemake/
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update -y conda
  - conda config --add channels gtcg
  - conda config --add channels bioconda
  - conda config --add channels nlesc
  - conda create -y -n wf
  - source activate wf
  - conda install -y snakemake xenon-cli
  - conda install -y pytest pytest-cov
script:
  - snakemake -C echo_run=1 enable_callers="['manta','delly','lumpy','gridss']"
  - find data -name *.vcf
  - pytest --cov=helper_functions
