dist: trusty
sudo: required
language: python
python:
  - "3.6"
services:
  - docker
env:
  global:
    - PREFIX=gtcg/sv-callers
    - TAG=dev
  matrix:
    - ECHO=1 MODE=s PORT=10022 SCH=gridengine
    - ECHO=1 MODE=p PORT=10023 SCH=gridengine
    - ECHO=1 MODE=s PORT=10024 SCH=slurm
    - ECHO=1 MODE=p PORT=10025 SCH=slurm
    - ECHO=0 MODE=s PORT=10022 SCH=gridengine
    - ECHO=0 MODE=p PORT=10023 SCH=gridengine
    - ECHO=0 MODE=s PORT=10024 SCH=slurm
    - ECHO=0 MODE=p PORT=10025 SCH=slurm
before_install:
  - cd snakemake/
install:
  - pip install -r test-requirements.txt
  - docker pull $PREFIX-$SCH:$TAG
  - docker run -d -p $PORT:22 --name $SCH-$MODE $PREFIX-$SCH:$TAG
  - sleep 10
  - docker ps -a
  - docker cp run.sh $SCH-$MODE:/home/xenon
script:
  - pytest --cov=helper_functions --cov-report=xml
  - docker exec -u xenon -t $SCH-$MODE /bin/bash run.sh $ECHO $MODE $SCH
after_success:
  - python-codacy-coverage -r coverage.xml
