language: python
sudo: false
dist: trusty
python:
  - "3.6"
before_install:
  - cd snakemake/
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update -q conda
  - conda create -n wf activate wf
  - conda install -c nlesc xenon-cli snakemake
script:
  - snakemake -C echo_run=1
  - find data -name *.vcf
