sudo: true
dist: trusty
language: python
python:
  - "3.6"
services:
  - docker
env:
  - PORT=10022 SCH=gridengine JID="\$JOB_ID"
  - PORT=10023 SCH=slurm JID="%j"
addons:
  apt:
    update: true
    packages:
      - sshpass
install:
  - docker pull gtcg/sv-callers-$SCH
  - docker run -d -p $PORT:22 gtcg/sv-callers-$SCH
  - sleep 10
  - docker ps -a
#before_script:
#  - ssh-keygen -R localhost
script:
  - |
    sshpass -p javagat ssh xenon@localhost -p $PORT \
      -o StrictHostKeyChecking=no \
      "/bin/bash -lc \"cd sv-callers/snakemake && snakemake -C echo_run=1 \
      --use-conda --latency-wait 30 --jobs --cluster \
      'xenon -vvv scheduler $SCH --location local:// submit --name smk.{rule} \
      --inherit-env --max-run-time 1 --working-directory . \
      --stderr stderr-$JID.log --stdout stdout-$JID.log' && ls\""
