dist: trusty
sudo: required
language: python
python:
  - "3.6"
services:
  - docker
env:
  - MODE=s PORT=10022 SCH=gridengine JID="\$JOB_ID"
  - MODE=g PORT=10023 SCH=gridengine JID="\$JOB_ID"
  - MODE=s PORT=10024 SCH=slurm JID="%j"
  - MODE=g PORT=10025 SCH=slurm JID="%j"
#addons:
#  apt:
#    update: true
#    packages:
#      - sshpass
before_install:
  - docker pull gtcg/sv-callers-$SCH
  - docker run -d -p $PORT:22 --name $SCH-$MODE gtcg/sv-callers-$SCH
  - sleep 10
  - docker ps -a
install: true
script:
  - docker exec -t $SCH-$MODE "printenv && echo $(hostname) | qsub"
