dist: xenial
sudo: required
language: python
python:
  - "3.7"
services:
  - docker
env:
  global:
    - PREFIX=gtcg/xenon
  matrix:
    - ECHO=0 MODE=s PORT=10020 SCH=gridengine TAG=6
    - ECHO=0 MODE=p PORT=10021 SCH=gridengine TAG=6
    - ECHO=0 MODE=s PORT=10022 SCH=slurm TAG=19
    - ECHO=0 MODE=p PORT=10023 SCH=slurm TAG=19
install:
  - pip install -r test-requirements.txt
  - docker run -d -p $PORT:22 --name $SCH-$TAG-$MODE $PREFIX-$SCH:$TAG
  - sleep 10
  - docker ps -a
  - docker cp ./ $SCH-$TAG-$MODE:/home/xenon
  - docker exec -t $SCH-$TAG-$MODE chown -R xenon:xenon /home/xenon
  - docker exec -u xenon -t $SCH-$TAG-$MODE ./install.sh
script:
  - cd snakemake && pytest --cov=helper_functions --cov-report=xml
  - docker exec -u xenon -t $SCH-$TAG-$MODE ./run.sh $ECHO $MODE $SCH
after_success:
  - python-codacy-coverage -r coverage.xml
