dist: xenial
sudo: required
language: python
python:
  - "3.7"
services:
  - docker
env:
  global:
    - PREFIX=gtcg/sv-callers
    - TAG=latest
  matrix:
    - ECHO=0 MODE=s PORT=10020 SCH=gridengine
    - ECHO=0 MODE=p PORT=10021 SCH=gridengine
    - ECHO=0 MODE=s PORT=10022 SCH=slurm
    - ECHO=0 MODE=p PORT=10023 SCH=slurm
install:
  - pip install -r test-requirements.txt
  - docker run -d -p $PORT:22 --name $SCH-$MODE $PREFIX-$SCH:$TAG
  - sleep 10
  - docker ps -a
script:
  - cd snakemake && pytest --cov=helper_functions --cov-report=xml
  - docker exec -u xenon -t $SCH-$MODE ./run.sh $ECHO $MODE $SCH
after_success:
  - python-codacy-coverage -r coverage.xml
