sudo: true
dist: trusty
language: python
python:
  - "3.6"
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y sshpass
install:
  - docker pull gtcg/sv-callers-gridengine
  - docker pull gtcg/sv-callers-slurm
  - docker run -d -p 10022:22 gtcg/sv-callers-gridengine
  - docker run -d -p 10023:22 gtcg/sv-callers-gridengine
  - docker run -d -p 10024:22 gtcg/sv-callers-slurm
  - docker run -d -p 10025:22 gtcg/sv-callers-slurm
  - sleep 10
  - docker ps -a
  - ssh-keygen -R xenon@localhost
script:
  - |
    echo "=== Run workflow in somatic mode on GridEngine cluster ==="
    sshpass -p javagat ssh -o StrictHostKeyChecking=no \
      -p 10022 xenon@localhost \
      "/bin/bash -l -c 'cd sv-callers/snakemake; . activate wf; snakemake -C echo_run=1 mode=s'"
  - |
    echo "=== Run workflow in germline mode on GridEngine cluster ==="
    sshpass -p javagat ssh -o StrictHostKeyChecking=no \
      -p 10023 xenon@localhost \
      "/bin/bash -l -c 'cd sv-callers/snakemake; . activate wf; snakemake -C echo_run=1 mode=g'"
  - |
    echo "=== Run workflow in somatic mode on Slurm cluster ==="
    sshpass -p javagat ssh -o StrictHostKeyChecking=no \
      -p 10024 xenon@localhost \
      "/bin/bash -l -c 'cd sv-callers/snakemake; . activate wf; snakemake -C echo_run=1 mode=s'"
  - |
    echo "=== Run workflow in germline mode on Slurm cluster ==="
    sshpass -p javagat ssh -o StrictHostKeyChecking=no \
      -p 10025 xenon@localhost \
      "/bin/bash -l -c 'cd sv-callers/snakemake; . activate wf; snakemake -C echo_run=1 mode=g'"
