echo_run: 0 # run SV callers [0] or vanilla jobs [1]

# file path to the reference genome in FASTA (excl. file suffix)
genome_path: data/fasta/Homo_sapiens.GRCh37.GATK.illumina

file_exts:
  fasta: .fasta
  fasta_idx:
    - .fasta.fai # faidx index file
    - .fasta.bwt # bwa v0.6.x
    - .fasta.amb # index files
    - .fasta.ann #
    - .fasta.pac #
    - .fasta.sa  #
  bam: .bam
  bam_idx: .bai

samples: samples.csv # list of tumor-normal sample pairs (*.bam files)

sv_callers:
  manta:
    enabled: true
    threads: 24
    memory: 10240 # MB
    tmpspace: 0 # min. temporary disk space in MB
    outdir: manta_out # relative to SAMPLE_DIR (see samples.csv)

  delly:
    enabled: true
    threads: 2
    memory: 10240 # MB
    tmpspace: 0 # MB
    outdir: delly_out
    sv_types:
        - BND
        - DEL
        - DUP
        - INS
        - INV

  lumpy:
    enabled: true
    threads: 1
    memory: 16384 # MB
    tmpspace: 1024 # MB
    outdir: lumpy_out

  gridss:
    enabled: true
    threads: 24
    memory: 49152 # MB
    tmpspace: 10240 # MB
    outdir: gridss_out
