name: continuous_integration
on: ["push", "pull_request"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        modes: ["s", "p"]
        schedulers: ["gridengine", "slurm"]
    env:
      NAME: ${{ matrix.schedulers }}-${{ matrix.modes }}
      IMAGE: gtcg/sv-callers-${{ matrix.schedulers }}:latest
      ARGS: 0 ${{ matrix.modes }} ${{ matrix.schedulers }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Python info
        run: |
          which python
          python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt
      - name: Show pip list
        run: pip list
      - name: Run unit tests
        run: |
          pytest --cov=helper_functions --cov-report=xml
          mv coverage.xml ${{ github.workspace }}
        working-directory: snakemake
      - name: Run workflow
        run: |
          docker run -d -p 10000:22 --name $NAME $IMAGE
          sleep 10
          docker ps -a
          docker exec -u xenon -t $NAME bash -c "cd sv-callers && ./run.sh $ARGS"
      - name: Upload coverage report to Codacy
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
